Add yacht
exercism/wren pull request #196
Opened 2024-06-13 06:08 UTC by BNAndras

For #48in24.

2024-06-13 11:44 UTC, glennj requested changes

2024-06-13 11:44 UTC, glennj commented on exercises/practice/yacht/wren_modules/wren-testie
This does not appear in other exercises.

2024-06-13 12:59 UTC, BNAndras commented on exercises/practice/yacht/wren_modules/wren-testie
Oops. Should I add it to gitignore?

2024-06-13 14:41 UTC, glennj commented on exercises/practice/yacht/wren_modules/wren-testie
It appears to be there already: https://github.com/exercism/wren/blob/main/.gitignore

Unless the leading slash is wrong

2024-06-14 17:45 UTC, BNAndras commented on exercises/practice/yacht/wren_modules/wren-testie
I removed the folder from the index and the updated gitignore seems to be working

2024-06-14 18:24 UTC, kotp commented on .gitignore
> +wren_modules/
```suggestion
wren_modules/

```

2024-06-14 19:30 UTC, kotp approved these changes

2024-06-14 20:04 UTC, glennj approved these changes

2024-06-14 20:04 UTC, glennj commented on exercises/practice/yacht/.meta/proof.ci.wren
> +  static score(dice, category) {
If this was a mentoring session, I'd have something to say about the length of this method ;)

2024-06-14 20:04 UTC, merged

2024-06-14 20:04 UTC, glennj commented
Thank you @BNAndras!