add strain
exercism/wren pull request #206
Opened 2024-07-10 04:55 UTC by BNAndras

2024-07-10 15:06 UTC, glennj requested changes

2024-07-10 15:06 UTC, glennj commented on config.json
The same functionality for this exercise also shows up in `list-ops`. Can you please make sure that `strain` appears earlier than list-ops, with a lower difficulty?

2024-07-10 15:06 UTC, glennj commented on exercises/practice/strain/.meta/proof.ci.wren
> +    return keep(list, Fn.new { |x| !predicate.call(x) })
Perhaps?
```suggestion
    return keep(list) { |x| !predicate.call(x) }
```

2024-07-10 15:06 UTC, glennj commented on exercises/practice/strain/strain.spec.wren
> +      Expect.value(Strain.keep([], predicate)).toEqual([])
more idiomatic to pass the predicate as a block (https://wren.io/functions.html#block-arguments):
```suggestion
      var actual = Strain.keep([]) { |x| true }
      Expect.value(actual).toEqual([])
```

2024-07-10 15:06 UTC, glennj commented
This might be an opportunity to add an instructions.append.md file pointing students to [the Fn class](https://wren.io/modules/core/fn.html#call(args...)) and the `call` method.

2024-07-10 15:13 UTC, BNAndras commented on config.json
I'll take a look tomorrow. Thanks for the review

2024-07-12 18:05 UTC, BNAndras commented
Updated

2024-07-12 18:12 UTC, glennj approved these changes

2024-07-12 18:13 UTC, glennj commented
Very nice, thank you.

2024-07-12 18:13 UTC, merged